export default {
  SET_ANIMAL_PREFERENCE: "SET_ANIMAL_PREFERENCE",
  SAVE_PET: "SAVE_PET",
  REMOVE_PET: "REMOVE_PET",
  SET_PROFILE: "SET_PROFILE",
  SET_AGE_RANGE: "SET_AGE_RANGE",
  DISPLAY_SITE_MESSAGE: "DISPLAY_SITE_MESSAGE"
};
